services:
  db:
    image: mysql:latest
    container_name: base-ayd1
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ayd1
    networks:
    - ayd1-network

  backend:
    image: findlesscopy/backend-ayd1:latest
    container_name: backend-ayd1
    ports:
    - "3000:3000"
    depends_on:
    - db
    networks:
    - ayd1-network

networks:
  ayd1-network:
    driver: bridge