services:
  backend:
    image: findlesscopy/backend-ayd1:4
    container_name: backend
    ports:
      - "3001:3001"
    networks:
      - ayd1_network
  frontend:
    image: findlesscopy/frontend-ayd1:12
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - ayd1_network
    depends_on:
      - backend
networks:
  ayd1_network:
      driver: bridge